// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2J7Y3iW4GD2l-JB62oVSql8pqKy0PP9M',
    appId: '1:35470134767:web:603658af7c83f7b65b7a1a',
    messagingSenderId: '35470134767',
    projectId: 'shinya-f31ce',
    authDomain: 'shinya-f31ce.firebaseapp.com',
    databaseURL: 'https://shinya-f31ce-default-rtdb.firebaseio.com',
    storageBucket: 'shinya-f31ce.firebasestorage.app',
    measurementId: 'G-JLB5XPCMRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHpIWRRqT3XwK0f_2LtYhHCO7mx09LszM',
    appId: '1:35470134767:android:2596bf011572bf035b7a1a',
    messagingSenderId: '35470134767',
    projectId: 'shinya-f31ce',
    databaseURL: 'https://shinya-f31ce-default-rtdb.firebaseio.com',
    storageBucket: 'shinya-f31ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfofQKCTsrT3wTpVbXuBhFpf2JYqJsLU',
    appId: '1:35470134767:ios:15744831ba511f985b7a1a',
    messagingSenderId: '35470134767',
    projectId: 'shinya-f31ce',
    databaseURL: 'https://shinya-f31ce-default-rtdb.firebaseio.com',
    storageBucket: 'shinya-f31ce.firebasestorage.app',
    iosBundleId: 'com.example.untitled12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfofQKCTsrT3wTpVbXuBhFpf2JYqJsLU',
    appId: '1:35470134767:ios:15744831ba511f985b7a1a',
    messagingSenderId: '35470134767',
    projectId: 'shinya-f31ce',
    databaseURL: 'https://shinya-f31ce-default-rtdb.firebaseio.com',
    storageBucket: 'shinya-f31ce.firebasestorage.app',
    iosBundleId: 'com.example.untitled12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2J7Y3iW4GD2l-JB62oVSql8pqKy0PP9M',
    appId: '1:35470134767:web:82ce551e93fc3f885b7a1a',
    messagingSenderId: '35470134767',
    projectId: 'shinya-f31ce',
    authDomain: 'shinya-f31ce.firebaseapp.com',
    databaseURL: 'https://shinya-f31ce-default-rtdb.firebaseio.com',
    storageBucket: 'shinya-f31ce.firebasestorage.app',
    measurementId: 'G-NGK09NGO1D',
  );
}
